Repository ruxailab/RUXAILAB, pull requests merged in 2025-03, with the labels that each got.

#596 Fix layout overflow and incorrect margin affecting bottom cards in ManagerView.vue file
  src/views/admin/ManagerView.vue
Labels: Enhancement, Good first issue, Review, good for wannabe gsocers, waiting-for-contributor

#601 Enhanced CSS Styling for Help Center Section 🎨✨
  src/views/public/Help.vue
Labels: good for wannabe gsocers, doing, discussion

#725 Feat: Automate Issue Creation from SonarCloud Analysis
  .github/workflows/sonarcloud_issue_creator.yml
  sonarcloud_to_github.py
Labels: Question, waiting-for-contributor

#610 "Save and Leave" Functionality to Ease usability of software
  src/components/atoms/LeaveAlert.vue
  src/locales/ar.json
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/hi.json
  src/locales/ja.json
  src/locales/pt_br.json
  src/locales/ru.json
  src/locales/zh.json
  src/views/admin/SettingsView.vue
Labels: waiting-for-contributor
